### ISSUE TITLE
Add validations to login and signup

### ISSUE THREAD

**Issue by idanstark42** [rpg-apps/characters#11]
* username exists?
* password strong enough?
* confirmation match?

**Comment by idanstark42** [comment]
Our backend is Mongo Realm app. It's a serverless MongoDB backend with authentication and a lot of other features built in, ran by mongo themselves and works with Atlas.
If you need authorization there tell me, but this issue regards only client side validations.

**Comment by A-BMT02** [comment]
Is the frontend in React ?

**Comment by idanstark42** [comment]
Yes. You can see the login forms as it is generated in the `components/contexts/auth-cotext.jsx` file

**Comment by A-BMT02** [comment]
Cant seem to run the app . I get this error 
"The react-scripts package provided by Create React App require dependency:

  "babel-jest": "^26.6.0"

Don't try to install it manually: your package manager does matically.
However, a different version of babel-jest was detected high in the tree:.............."

I tried to resole it but i could'nt
Do you have an idea on how to fix it ?

**Comment by idanstark42** [comment]
Interesting....
Can you write down step by step what you did, including each command you ran?

**Comment by A-BMT02** [comment]
npm install 
npm start

I've had this issue before but i was able to solve it by deleting the node module and running npm install again

Unfortunately for this project that doesnt solve it

**Comment by idanstark42** [comment]
Can you try running it with yarn instead?
npm i yarn -g
yarn install
yarn start

**Comment by A-BMT02** [comment]
Still not working .
I'm getting the same error

**Comment by idanstark42** [comment]
Do you have `babel-jest` installed on your computer elsewhere? Maybe globally? Or do you have another `node_modules` folder somewhere up the tree?
People write, for instance [here](https://github.com/facebook/create-react-app/issues/8636), that the problem is that there is another `node_modules` folder with a different version of the module somewhere in the folder tree.

**Comment by A-BMT02** [comment]
Thanks!
Fixed it .
Turns out i had a node_modules folder ON MY DESKTOP .

I'm still getting an error on the compiler though 

./src/games/dungeon-world/core.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./src/games/dungeon-world/core.scss)
Cannot find file: 'Bolster.png' does not match the corresponding name on disk: '.\src\games\dungeon-world\images\moves\bolster.png'.
> 

>

**Comment by idanstark42** [comment]
That's really interesting....
You need to change the name of the image file to stay with a capital letter. `Bolster.png`.
I wonder why it's lower case... I'll look into that

**Comment by vramani1121** [comment]
hey,
i am begginer to contribute here. but  i am stuck at setup environment of this code base. so, can you suggest me right path for executing code.

**Comment by idanstark42** [comment]
Hi @vramani1121.
This thread is meant for the given issue. If you're having problems starting the program, please contact me directly at idanstark42@gmail.com.
Also, please write what you tried to do in order to start it, and what didn't work as expected. If you're having @A-BMT02's problem, please let's continue here.

@A-BMT02, I have changed the filenames to be correct here in the master branch. Please make sure to pull it before trying to run the software again, and tell me if anything else doesn't work.

**Comment by A-BMT02** [comment]
I pulled the new repository and i'm still getting an error after running npm start

./node_modules/@rpg-apps/rpg-js/models/mechanism/formula.js 172:16
Module parse failed: Unexpected token (172:16)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     const outcome = character.getValueFromType(rawOutcome, 'range') || character.getValueFromType(rawOutcome, 'number');
| 
>     if (outcome?.includes(value) || outcome === value) {
|       return await character.getRawValue({
|         raw: String(outcomes[rawOutcome]),

**Comment by idanstark42** [comment]
I added a babel plugin for safe navigation. Please try `pull`, `install` and `start` again.

**Comment by jtcode12** [comment]
hey man, can I give this a go?

**Comment by idanstark42** [comment]
@jtcode12 sure, just submit the pull request when you're ready. If you have any questions or issues feel free to contact :)
@A-BMT02 are you still working on this? In case of lack of response I'll unassign you.
